version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/functions"
    update_schedule: "live"

update_configs:
  - package_manager: "javascript"
    directory: "/tools"
    update_schedule: "live"
